### ISSUE TITLE
0.0.6 to 1.0.1

### ISSUE THREAD

**Issue by PrzemyslawKlys** [DigitalAXPP/jwtPS#32]
I was happy user of jwtPS 0.0.6 version. I've used this method to generate JTW Token for a project of mine https://github.com/EvotecIT/PowerFederatedDirectory

I was using: 
```powershell
Import-Module jwtPs -MaximumVersion 0.6.0 -Force

$PrivateKeyPath = "C:\Support\Important\Password-FederatedDirectory-Key.txt"
$Key = Get-Content -Raw -LiteralPath $PrivateKeyPath # Saved private key from Federated Directory
$Payload = @{
    aud     = "eyJhbGciOin" # Key from Federated Directory
    iss     = "0snz1xgp7inutc" # Issuer name from Federated Directory
    scope = @("directoryKey")
}
$JWT = New-Jwt -PrivateKey $Key -Algorithm RS256 -Payload $Payload
$JWT
```

Now with new version things stopped working. So I tried to convert it to newest version and having troubles to accomplish that.

Get-Help New-JTW no longer shows PrivateKey as parameter. 

```powershell
    New-Jwt -Algorithm <cryptographyType> -Payload <Hashtable> -Secret <String> [<CommonParameters>]
```

In the example in readme it still says PrivateKey. I assume it's now Secret right? 

Now my bigger problem is that I only have PrivateKey, and you only support the PEM format, so it's no longer accepting my input. 

```powershell
$PrivateKeyPath = "C:\Support\Important\Password-FederatedDirectory-Key.txt"
$Key = Get-Content -Raw -LiteralPath $PrivateKeyPath # Saved private key from Federated Directory
$Payload = @{
    aud   = "eyJh" # Key from Federated Directory
    iss   = "0snz" # Issuer name from Federated Directory
    scope = @("directoryKey")
}

$encryption = [jwtFunction+encryption]::SHA256
$algorithm = [jwtFunction+algorithm]::RSA
$alg = [jwtFunction+cryptographyType]::new($algorithm, $encryption)

$JWT = New-Jwt -Payload $Payload -Algorithm $alg -Secret $Key
$JWT
```

But that just throws error `The filename, directory name, or volume label syntax is incorrect.`. Any tips on how to migrate? 

Also it seems that PowerShell 5.1 was dropped. So that is that :-(

**Comment by DigitalAXPP** [comment]
Hi Przemyslaw,
My apologies for the issues which the new version caused but I am surprised that the old version 0.0.6.0 doesn't work anymore. I didn't change anything about it.
Yes, with the new version, I am using F# with .NET Core which then doesn't allow anymore anything below PowerShell 6.
I changed the parameter name from Privatekey to Secret because HMAC doesn't use a key. 
Could you please tell me what private key type you use? I will try to include it in the library.

**Comment by PrzemyslawKlys** [comment]
The old version works! It's that you have to "know" about the change and force to use 0.0.6, and I only found out about it when some users complained about issues they can't generate tokens anymore ;)

Your example is wrong:
![image](https://user-images.githubusercontent.com/15063294/200118290-1b5fa0f3-03a3-4690-bf91-6af951d4fbe2.png)

To be honest, I am not sure what private key type it is. I download the private key from [Federated.Directory](https://www.federated.directory/) but what sort of key they offer - I have no clue 

![image](https://user-images.githubusercontent.com/15063294/200118337-13de7d1c-6cb7-44da-96cb-eee213377770.png)

**Comment by DigitalAXPP** [comment]
In the newest version (v1.1.0) the private key as well as the PEM key file are accepted.
PowerShell 6 as minimum version is unchanged as F# is used with .NET Core.
